### ISSUE TITLE
java.lang.ClassNotFoundException: fuck_the_regulations_320.Ob1

### ISSUE THREAD

**Issue by lixinhan** [ja-netfilter/ja-netfilter#100]
when i run PHPStorm  

2022-02-09 17:26:25.522 phpstorm[31735:1434933] allVms required 1.8*,1.8+
2022-02-09 17:26:25.526 phpstorm[31735:1434936] Current Directory: /Users/lixinhan
2022-02-09 17:26:25.526 phpstorm[31735:1434936] parseVMOptions: PHPSTORM_VM_OPTIONS = (null)
2022-02-09 17:26:25.526 phpstorm[31735:1434936] fullFileName is: /Applications/PhpStorm.app/Contents/bin/phpstorm.vmoptions
2022-02-09 17:26:25.526 phpstorm[31735:1434936] fullFileName exists: /Applications/PhpStorm.app/Contents/bin/phpstorm.vmoptions
2022-02-09 17:26:25.526 phpstorm[31735:1434936] parseVMOptions: /Applications/PhpStorm.app/Contents/bin/phpstorm.vmoptions
2022-02-09 17:26:25.526 phpstorm[31735:1434936] parseVMOptions: /Applications/PhpStorm.app.vmoptions
2022-02-09 17:26:25.532 phpstorm[31735:1434936] parseVMOptions: /Users/lixinhan/Library/Application Support/JetBrains/PhpStorm2021.3/phpstorm.vmoptions
2022-02-09 17:26:25.532 phpstorm[31735:1434936] parseVMOptions: platform=19 user=2 file=/Users/lixinhan/Library/Application Support/JetBrains/PhpStorm2021.3/phpstorm.vmoptions

  ============================================================================

    ja-netfilter-v2.2.3

    A javaagent framework :)

    https://github.com/ja-netfilter/ja-netfilter

  ============================================================================

Exception in thread "main" java.lang.ExceptionInInitializerError
	at fuck_the_regulations_320.e9.<clinit>(e9.java:15)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.util.ConcurrentModificationException: java.lang.ClassNotFoundException: fuck_the_regulations_320.Ob1
	at fuck_the_regulations_320.aZ.<clinit>(aZ.java:82)
	... 7 more
Caused by: java.lang.ClassNotFoundException: fuck_the_regulations_320.Ob1
	at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:229)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at fuck_the_regulations_320.aZ.<clinit>(aZ.java:127)
	... 7 more
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
[1]    31735 abort      /Applications/PhpStorm.app/Contents/MacOS/phpstorm

How to solve this problem？

**Comment by pengzhile** [comment]
去掉老的javaagent
