### ISSUE TITLE
不能打开多个IDE

### ISSUE THREAD

**Issue by tille1229** [ja-netfilter/ja-netfilter#48]
### 不能打开多个IDE
当我为idea/webstorm 设置 javaagent 时，**只有一个IDE可以正常运行，另一个会卡住死**;
尝试过以下方法：
> * 拷贝多份ja-netfilter，分别为不同的IDE进行设置;
> * 尝试清空另外的config.txt中的配置;

均没效果;
idea.log中启动错误日志：
```
2021-12-16 18:44:41,090 [    984]   INFO - llij.ide.plugins.PluginManager - Loaded bundled plugins: IDEA CORE (213.5744.178), TextMate Bundles (213.5744.178), IntelliLang (213.5744.178), Images (213.5744.178), Windows 10 Light Theme (213.5744.178), Diagrams (213.5744.178), Database Tools and SQL (213.5744.178), DataGrip Customization (213.5744.178), DataGrip Help (213.5744.178), Git (213.5744.178), Machine Learning in Search Everywhere (213.5744.178) 
2021-12-16 18:44:41,090 [    984]   INFO - llij.ide.plugins.PluginManager - Loaded custom plugins: Chinese (Simplified) Language Pack / 中文语言包 (213.241), IdeaVim (1.9.1), IdeaVimExtension (1.5.0) 
2021-12-16 18:44:41,322 [   1216]   INFO - ication.options.PathMacrosImpl - Loaded path macros: {} 
2021-12-16 18:44:41,504 [   1398]   INFO -        #com.intellij.idea.Main - JNA library (64-bit) loaded in 1249 ms 
2021-12-16 18:44:41,511 [   1405]   INFO - til.net.ssl.CertificateManager - Default SSL context initialized 
2021-12-16 18:44:41,511 [   1405]   INFO - penapi.util.io.win32.IdeaWin32 - Native filesystem for Windows is operational 
2021-12-16 18:44:41,590 [   1484]   INFO - intellij.diagnostic.JitWatcher - JIT compilation state checking enabled 
2021-12-16 18:44:41,616 [   1510]   INFO - intellij.util.io.FilePageCache - lower=100; upper=500; buffer=10; max=730 
2021-12-16 18:44:43,097 [   2991]  ERROR - llij.ide.plugins.PluginManager - java.net.BindException: Address already in use: bind 
java.util.concurrent.CompletionException: java.net.BindException: Address already in use: bind
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.net.BindException: Address already in use: bind
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:455)
	at java.base/sun.nio.ch.Net.bind(Net.java:447)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:134)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by pengzhile** [comment]
这种情况不使用javaagent都会如此，一般重启电脑就好了。
