### ISSUE TITLE
Exception while opening rider

### ISSUE THREAD

**Issue by abdulrahman-b-h** [ja-netfilter/ja-netfilter#55]
There is an exception thrown from the tool:

Exception in thread "main" java.lang.ExceptionInInitializerError
        at fuck_the_regulations_320.e9.<clinit>(e9.java:15)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.util.ConcurrentModificationException: java.lang.ClassNotFoundException: fuck_the_regulations_320.ub1
        at fuck_the_regulations_320.aZ.<clinit>(aZ.java:82)
        ... 7 more
Caused by: java.lang.ClassNotFoundException: fuck_the_regulations_320.ub1
        at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:229)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at fuck_the_regulations_320.aZ.<clinit>(aZ.java:127)
        ... 7 more
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at ./src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed

**Comment by pengzhile** [comment]
先把老的jetbrains-agent从配置文件拿掉

abdulrahman-b-h ***@***.***>于2021年12月19日 周日05:47写道：

**Comment by LiucongjieA** [comment]
怎么拿掉配置？我已经删除了jetbrains-agent文件，之后报错
![image](https://user-images.githubusercontent.com/25733058/146674585-8ba45d90-0059-4af3-83f5-f345842e082d.png)

**Comment by googleweb** [comment]
> 怎么拿掉配置？我已经删除了jetbrains-agent文件，之后报错 ![image](https://user-images.githubusercontent.com/25733058/146674585-8ba45d90-0059-4af3-83f5-f345842e082d.png)

你的代理设置需要改，-javaagent: 参数需要改成现在的，或者去掉，不然你的程序打不开了
